// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCA2U7VtTRCTAWTDMtEZQJMWCZA-pIm81M',
    appId: '1:922488826046:web:e4f633b747e3224f7456ef',
    messagingSenderId: '922488826046',
    projectId: 'lumi-home-f1cca',
    authDomain: 'lumi-home-f1cca.firebaseapp.com',
    storageBucket: 'lumi-home-f1cca.appspot.com',
    measurementId: 'G-WM62SNYGM6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDH4pOpkx2zVkzma0xj4IqSIlTxbO10P4',
    appId: '1:922488826046:android:d2eeb8d67ec532f07456ef',
    messagingSenderId: '922488826046',
    projectId: 'lumi-home-f1cca',
    storageBucket: 'lumi-home-f1cca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdsWttRRCmqlFbxbYK678wMfnEfcVjhw8',
    appId: '1:922488826046:ios:e242db31e44eb78a7456ef',
    messagingSenderId: '922488826046',
    projectId: 'lumi-home-f1cca',
    storageBucket: 'lumi-home-f1cca.appspot.com',
    iosBundleId: 'com.example.lumihome',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdsWttRRCmqlFbxbYK678wMfnEfcVjhw8',
    appId: '1:922488826046:ios:e242db31e44eb78a7456ef',
    messagingSenderId: '922488826046',
    projectId: 'lumi-home-f1cca',
    storageBucket: 'lumi-home-f1cca.appspot.com',
    iosBundleId: 'com.example.lumihome',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCA2U7VtTRCTAWTDMtEZQJMWCZA-pIm81M',
    appId: '1:922488826046:web:da11dc5bf8e265937456ef',
    messagingSenderId: '922488826046',
    projectId: 'lumi-home-f1cca',
    authDomain: 'lumi-home-f1cca.firebaseapp.com',
    storageBucket: 'lumi-home-f1cca.appspot.com',
    measurementId: 'G-5WD1STSMXD',
  );
}
